# update pipeline:
# fly -t anz sp -c pipeline-deploy.yml -p anz-test-deploy  

resources:
  - name: golang-version
    type: git
    check_every: 5m
    webhook_token: ((common.webhook-token))
    source:
      uri: https://github.com/SouthbankSoftware/provendb-api-gateway.git
      branch: master
      username: ((common.git-username))
      password: ((common.git-password))
      disable_ci_skip: false
  - name: version
    type: semver
    source:
      driver: gcs
      bucket: provendb-ci
      json_key: ((common.service-account))
      key: provendb-api-gateway/version/version.txt
      initial_version: 0.0.0
  - name: docker-registry
    type: docker-image
    source:
      repository: asia.gcr.io/provendb/provendb-api-gateway
      username: _json_key
      password: ((common.service-account))
  - name: golang
    type: docker-image
    source:
      repository: golang
      tag: 1.12.6
  - name: provendb-api-gateway-hotfix
    type: git-multibranch
    source:
      uri: https://((common.git-username)):((common.git-password))@github.com/SouthbankSoftware/provendb-api-gateway.git
      branches: hotfix/.*
      check_every: 5m    
  - name: mongodb
    type: docker-image
    source:
      repository: mongo
      tag: 4.0

jobs:
  - name: build-and-deploy
    serial: true
    plan:
      - get: provendb-api-gateway
        trigger: true
      - put: github-status
        params:
          commit: provendb-api-gateway
          state: pending
      - get: version
        params: { bump: patch }
      - get: golang
        params: { save: true }
      - put: docker-registry
        params:
          additional_tags: provendb-api-gateway/.git/short_ref
          build: provendb-api-gateway
          tag_as_latest: true
          tag_file: version/number
        get_params: { skip_download: true }
      - put: version
        params: { file: version/number }
    on_failure:
      do:
        - put: slack
          params:
            alert_type: failed
            text: ((slack.guan))
        - put: github-status
          params:
            commit: provendb-api-gateway
            state: failure
    on_abort:
      do:
        - put: slack
          params:
            alert_type: failed
            text: Aborted. ((slack.guan))
        - put: github-status
          params:
            commit: provendb-api-gateway
            state: failure
    on_success:
      do:
        - put: slack
          params:
            alert_type: success
        - put: github-status
          params:
            commit: provendb-api-gateway
            state: success

  - name: build-and-deploy-hotfix
    serial: true
    plan:
      - get: provendb-api-gateway
        resource: provendb-api-gateway-hotfix
        trigger: true
      - get: mongodb
        params: { save: true }
      - get: golang
        params: { save: true }  
      - task: unit-test
        privileged: true
        file: provendb-api-gateway/ci/task-unit-test/task-unit-test.yml  
      - task: create-docker-tag
        file: provendb-api-gateway/ci/task-build-docker-tag.yml
      - put: docker-registry
        params:
          build: provendb-api-gateway
          tag_file: provendb-api-gateway/docker_tag
        get_params: { skip_download: true }      
    on_failure:
      do:
        - put: slack
          params:
            alert_type: failed
            text: ((slack.koustubh))
    on_abort:
      do:
        - put: slack
          params:
            alert_type: failed
            text: Aborted. ((slack.koustubh))  