platform: linux
image_resource:
  type: docker-image
  source: { repository: amidos/dcind, tag: latest }
inputs:
  - name: golang-version
run:
  path: bash
  args:
    - -exc
    - |
      source /docker-lib.sh
      start_docker
     
      # run logic via docker compose
      cd  golang-version/test-2
      docker-compose -f ci/docker-compose-test.yml run test