apiVersion: v1
kind: Service
metadata:
  name: anz-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "anz-technical-test-2.selectorLabels" . | nindent 4 }}
