# update pipeline:
# fly -t anz sp -c pipeline-deploy.yml -p anz-test-deploy  
resource_types:
  - name: github-status
    type: docker-image
    source:
      repository: resource/github-status

resources:
  - name: golang-version
    type: git
    webhook_token: ((auth.webhook_token))
    source:
      uri: https://github.com/koustubh25/anz-technical-tests.git
      branch: master
      username: ((common.git-username))
      password: ((common.git-password))
      disable_ci_skip: false
  - name: version
    type: semver
    source:
      driver: gcs
      bucket: anz-golang-version
      json_key: ((common.service-account))
      key: version/version.txt
      initial_version: 0.0.0
  - name: docker-registry
    type: docker-image
    source:
      repository: us.gcr.io/prismatic-cider-277502/anz-golang-version-test-2
      username: _json_key
      password: ((common.service-account))

  - name: github-status
    type: github-status
    source:
      repo: koustubh25/anz-technical-tests
      access_token: ((auth.access_token))


jobs:
  - name: build-and-deploy
    serial: true
    plan:
      - get: golang-version
        trigger: true
      - get: version
        params: { bump: patch }
      - task: update-version-info
        file: golang-version/test-2/ci/tasks/write-tags-task.yml   
      - task: integration-tests
        file: golang-version/test-2/ci/tasks/integration-tests.yml   
        privileged: true
      - put: github-status
        params:
          path: golang-version
          state: pending  
      - put: docker-registry
        params:
          additional_tags: golang-version/.git/short_ref
          build: golang-version/test-2
          tag_as_latest: true
          tag_file: version/number
        get_params: { skip_download: true }
      - put: version
        params: { file: version/number }
    on_failure:
      do:
        - put: github-status
          params:
            path: golang-version
            state: failure
    on_success:
      do:
        - put: github-status
          params:
            path: golang-version
            state: success
